import type { FilterPreset } from "@/types";

export const builtInPresets: FilterPreset[] = [
  {
    id: "adventure-background",
    name: "Adventure Background",
    builtIn: true,
    description:
      "Balanced cell-shading for point-and-click backgrounds. Moderate outlines, soft smoothing.",
    settings: {
      presetId: "adventure-background",
      basePresetId: null,
      colourLevels: 6,
      edgeStrength: 0.65,
      edgeThickness: 1.5,
      edgeThreshold: 0.25,
      smoothing: 0.35,
      contrast: 1.1,
      saturation: 1.15,
      shadowBias: 0.0,
      lineColour: "#111111",
      preserveBackground: true,
      preserveTransparency: true,
    },
  },
  {
    id: "comic-ink",
    name: "Comic Ink",
    builtIn: true,
    description:
      "Bold outlines with high contrast and limited colour bands for a graphic novel look.",
    settings: {
      presetId: "comic-ink",
      basePresetId: null,
      colourLevels: 5,
      edgeStrength: 0.9,
      edgeThickness: 3.0,
      edgeThreshold: 0.15,
      smoothing: 0.1,
      contrast: 1.4,
      saturation: 1.1,
      shadowBias: 0.1,
      lineColour: "#0a0a0a",
      preserveBackground: false,
      preserveTransparency: true,
    },
  },
  {
    id: "soft-painted",
    name: "Soft Painted",
    builtIn: true,
    description: "Low outlines, heavier smoothing, and more colour bands for a hand-painted feel.",
    settings: {
      presetId: "soft-painted",
      basePresetId: null,
      colourLevels: 10,
      edgeStrength: 0.3,
      edgeThickness: 1.0,
      edgeThreshold: 0.35,
      smoothing: 0.7,
      contrast: 1.05,
      saturation: 1.0,
      shadowBias: -0.05,
      lineColour: "#322214",
      preserveBackground: true,
      preserveTransparency: true,
    },
  },
  {
    id: "pixel-friendly-flat",
    name: "Pixel-Friendly Flat",
    builtIn: true,
    description:
      "Strong colour reduction with minimal detail, suitable for low-resolution or retro pixel-art styles.",
    settings: {
      presetId: "pixel-friendly-flat",
      basePresetId: null,
      colourLevels: 4,
      edgeStrength: 0.7,
      edgeThickness: 1.0,
      edgeThreshold: 0.3,
      smoothing: 0.45,
      contrast: 1.2,
      saturation: 1.25,
      shadowBias: 0.0,
      lineColour: "#1a1a1a",
      preserveBackground: true,
      preserveTransparency: true,
    },
  },
  {
    id: "dark-neo-noir",
    name: "Dark Neo-Noir",
    builtIn: true,
    description: "Heavy black outlines, strong contrast, desaturated tones, and deep shadows.",
    settings: {
      presetId: "dark-neo-noir",
      basePresetId: null,
      colourLevels: 6,
      edgeStrength: 1.0,
      edgeThickness: 4.0,
      edgeThreshold: 0.12,
      smoothing: 0.2,
      contrast: 1.6,
      saturation: 0.7,
      shadowBias: 0.5,
      lineColour: "#0a0a0a",
      preserveBackground: false,
      preserveTransparency: true,
    },
  },
];
